### ISSUE TITLE
ruff failed   Cause: Failed to create cache file 

### ISSUE THREAD

**Issue by devendr4** [ChartBoost/ruff-action#10]
![image](https://github.com/ChartBoost/ruff-action/assets/39252256/001ee0bf-2073-44f2-9cd7-0eb208fa3a67)

I suddenly started getting  this issue when running the github action

```
installing ruff...
ruff failed
  Cause: Failed to create cache file '/home/runner/work/reportin/reportin/.ruff_cache/0.1.12/13271580516683047953'
  Cause: No such file or directory (os error 2)
```

**Comment by LoverCheng** [comment]
Hi bro. I find when I add the missing directory, then this script would be fun:

you can do it like below:
```
- uses: actions/checkout@v3
- run: mkdir -p /home/runner/work/reporting/reportin/.ruff_cache/0.1.12/
- uses: chartboost/ruff-action@v1
```

**Comment by devendr4** [comment]
> - run: mkdir -p /home/runner/work/reporting/reportin/.ruff_cache/0.1.12/

Thanks @LoverCheng this worked, but it's weird that it was working properly without that before

**Comment by LoverCheng** [comment]
> > * run: mkdir -p /home/runner/work/reporting/reportin/.ruff_cache/0.1.12/
> 
> Thanks @LoverCheng this worked, but it's weird that it was working properly without that before

Yeah, it's weird. I also do not know what has happened.

**Comment by brucearctor** [comment]
marking closed since 'working'
