### ISSUE TITLE
How to specify the ruff configuration file?

### ISSUE THREAD

**Issue by wu-clan** [ChartBoost/ruff-action#2]
Is it possible to add a with parameter: `toml`

to specify an existing configuration file

**Comment by brucearctor** [comment]
ruff picks up its config from a `pyproject.toml ` already -- are you hoping to use a toml from a different location?

**Comment by wu-clan** [comment]
Yes, my ruff configuration is separate and located in `.ruff.toml`

**Comment by brucearctor** [comment]
are you sure it doesn't pick up that file?  https://beta.ruff.rs/docs/configuration/#using-rufftoml looks like ruff.toml supported out of the box by ruff, which is what this project aims to do.

**Comment by brucearctor** [comment]
what flags/commands/arguments are you currently passing ruff for it to find your config file when you use ruff [ for example in pre-commit, or just manually on your development machine ]?

**Comment by wu-clan** [comment]
Sorry, ruff will automatically detect the '.ruff.toml' file locally. I am using it in pre-commit and I have ignored it here

**Comment by brucearctor** [comment]
so...  if I understand correctly, then ruff also picks up your toml file in this gh action without problem?

**Comment by wu-clan** [comment]
Use args: ['--config', '.ruff.toml'] in pre-commit

Use args: '--config .ruff.toml' here

Everything works fine 🎉

**Comment by brucearctor** [comment]
great!  

If we find this to be a significant pain point, or common use case for others, we can add an additional [ config] option in the action configuration.  But, yes, that would be my first suggestion -- glad it's working for you!
