### ISSUE TITLE
Is it possible to only fix/format the `diff` in the PR?

### ISSUE THREAD

**Issue by ma-sadeghi** [ChartBoost/ruff-action#21]

**Comment by brucearctor** [comment]
Probably?  Seems like that could be an option that could be added.  Is that something you'd be willing to contribute?

**Comment by ma-sadeghi** [comment]
Sure, I can take a crack at this this weekend

**Comment by ma-sadeghi** [comment]
Just an update: I do want to contribute, but it might not happen this weekend due to other commitments, just to adjust expectations :)

**Comment by brucearctor** [comment]
All good.  We're happy to accept contributions on whatever timelines are doable for people doing the [ volunteer ] work.  hope you're getting into something fun over the weekend -

**Comment by Vaibhav-Lodha** [comment]
@brucearctor wanted to understand 2 things. I might be able to contribute if time persists in the upcoming weeks - 
1. Currently, when we open a pull request, the default action runs on all files, and to build support for it, we need to change the current implementation, i.e. adding some flag like only git-diff
2. Secondly, we don't have to functionality like how Django Doctor or gitleaks comments in the file for the errors, is that right, all I could find is a output file in git action?
