### ISSUE TITLE
Who will maintain this repo?  

### ISSUE THREAD

**Issue by brucearctor** [ChartBoost/ruff-action#26]
Now that I am no longer with ChartBoost, who will be maintaining this repo?  

Perhaps we should give some permissions and/or redirect for the sake of the many users reliant on this?

ex, more than 1.2K public usages of 'chartboost/ruff-action' -->  https://github.com/search?q=chartboost%2Fruff-action&type=code

https://github.blog/2013-05-16-repository-redirects-are-here/

**Comment by brucearctor** [comment]
@CB-GuangyaoXie ?

**Comment by ma-sadeghi** [comment]
Sorry for the off-topic comment: Could you please review/merge #24? Thanks :)

**Comment by brucearctor** [comment]
I'll take a look when at computer:

* unclear whether I still have permissions. 

* need to look at your code, and consider risks if this introduces new dependencies

**Comment by brucearctor** [comment]
Update -- ya, def. don't have permissions.

I have suggested I am willing to accept transfer [ https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository ] to continue to maintain for the good of the community of users.

**Comment by ma-sadeghi** [comment]
Is there any point of contact at ChartBoost to initiate the transfer?

**Comment by augustelalande** [comment]
@charliermarsh would it make sense to pull this under the astral umbrella? Seems like a core functionality for the linter.

**Comment by charliermarsh** [comment]
Yeah, we can maintain an official GitHub Action.

**Comment by charliermarsh** [comment]
We can transfer it under Astral if someone has permissions to do so.

**Comment by augustelalande** [comment]
@daniel-barros ?

**Comment by zanieb** [comment]
👍 yeah I'm happy to maintain if it's transferred

**Comment by brucearctor** [comment]
Tbd if you need to fork, unclear that chartboost legal will be ok with transfer [ had requested ]   

Great to also get in gh action marketplace, while I was employed there I failed at getting needed approvals to get gh developer license signed which was a prerequisite 

Ideally transfer occurs to better serve/transition the community of users.   That is why I hadn't forked myself...  without transfer, the best place for this to fork/live is likely in Astral.

**Comment by charliermarsh** [comment]
I will give it a week or so. If we don't hear back, we'll just create a new repo in the Astral org.

**Comment by ffernandez92** [comment]
I had permission to merge the [PR](https://github.com/ChartBoost/ruff-action/pull/24). I think there is a bit of risk in adding an extra dependency, but it seems to be working fine. I'd like to wait until the repo is transferred so we can generate the release.
Let me know if I can help with anything

**Comment by vitaliyf** [comment]
Hopefully I'm not getting too ahead of myself - but can Astral also press the necessary buttons to become a "verified" publisher in the actions marketplace? One of the security options for GitHub actions within paid accounts is to [restrict 3rd party actions to only those published by verified publishers](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#allowing-select-actions-and-reusable-workflows-to-run), and some organizations require this for various supply-chain-security reasons.

They document the necessary steps here: https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by brucearctor** [comment]
@ffernandez92 -- ideally this winds up transferred to https://github.com/astral-sh ...  I think GY has permissions to do that [ I imagine you do not? ] but perhaps waiting on [ lack of? ] legal approval?  

There isn't anything company specific/proprietary in here.  Transfer would be the cleanest way to save the company from maintenance, AND esp. be kindest to the community by way of redirect, etc...  But 🤷 .

**Comment by zanieb** [comment]
Any updates from someone who works at ChartBoost? It'd be great to provide uninterrupted service for the users of this.

**Comment by brittag** [comment]
Thanks all for your thoughtful consideration of ensuring a smooth transition for this action! Just adding appreciation and encouragement as part of a team that uses it for our open source web application. :)

**Comment by nitishxp** [comment]
@charliermarsh Can you please help us on merging this https://github.com/ChartBoost/ruff-action/pull/29

**Comment by zanieb** [comment]
@nitishxp we cannot merge pull requests here — ChartBoost has not taken any action towards transferring the project.

**Comment by nitishxp** [comment]
@zanieb  can we shift that repo under astra, that defect is literally blocking us for most of the things

**Comment by zanieb** [comment]
@nitishxp we do not have control over transfer of this repository, as discussed above — ChartBoost needs to take action for a seamless transition.

We'll create our own action eventually, if it comes to that.

**Comment by ma-sadeghi** [comment]
The action is released under Apache 2, which is fairly permissive. Why not fork it under astral?

**Comment by zanieb** [comment]
If the repository is transferred instead, there won't be an interruption for existing users (usage will be redirected).

**Comment by brucearctor** [comment]
Last I heard from employees [ I am no longer there ], this was going
through legal approval process to transfer.   I can ask whether stuck, a
determination, or in-progress still.  Also, I believe one guy who can
merge/maintain is on vacation currently, so tbd.  Forking is permitted, not
the worst idea, but certainly much better if this can be transferred.

**Comment by charliermarsh** [comment]
I think if we find time to prioritize it before the transfer completes, and there's no clear timeline, we'll just fork. But if the transfer completes before we get to it, that's obviously preferable.

**Comment by DavidJFelix** [comment]
This repo has a github-actions bot actively closing open PRs because they're "stale" in the amount of time it's taking to transfer this. Can we just accept that there will be some loss of continuity and fork? When Chartboost finally gets back to this they can change the readme to direct people to the fork.

**Comment by charliermarsh** [comment]
Yeah we're just planning to fork it at this point. The bottleneck is finding time for us to prioritize taking over the action.

**Comment by brucearctor** [comment]
@charliermarsh -- if you want to fork it, I can commit to starting to maintain.  I am the original author but no longer have permissions/affiliation at/with ChartBoost.  I am confident I can get them to write a README informing of the fork.  Sounds like unlikley to get prioritization to get attention of lawyers.   If that makes sense, later this week I should also be able to update docs via PRs to point to new location.  

Steps:
* FORK
* Grant Me Permissions
* I'll work with ChartBoost to update the README to point to new location
* I'll submit PR to update docs to point to new location
* etc

Do advise if you want me to help move this forward.

**Comment by DavidJFelix** [comment]
Also happy to help.

**Comment by CB-GuangyaoXie** [comment]
Creating a fork is the best course of action for this project. Please submit a README update PR when you have the new location created.

**Comment by DavidJFelix** [comment]
@charliermarsh sorry for my impatience, I know everyone here is donating their time, but it feels like we have willpower to make this change and are getting mired down in process.

It sounds like @brucearctor is willing and able to manage these changes for astral, so we should be able to achieve this with 3 actions in the github UI that should take no more than a few minutes:

* [Fork the repo to astral-sh](https://github.com/ChartBoost/ruff-action/fork)
* [Add @brucearctor as an outside collaborator to astral-sh (this link won't resolve until you fork)](https://github.com/astral-sh/ruff-action/settings/access)
* Change permissions on collaborator as needed. I think "maintainer" is right but "write" may be enough.

**Comment by charliermarsh** [comment]
I'll try to get to it today.

**Comment by charliermarsh** [comment]
I've forked the action here: https://github.com/astral-sh/ruff-action. I'd like to make some substantial changes to it but I don't want that to block the fork.

**Comment by DavidJFelix** [comment]
Thanks for getting this done @charliermarsh ! I'll take some time later today to try to get some of the issues and auto-closed PRs that are here posted over there so we can at least discuss.

**Comment by brucearctor** [comment]
> I've forked the action here: https://github.com/astral-sh/ruff-action. I'd like to make some substantial changes to it but I don't want that to block the fork.

@charliermarsh -- I never saw any message after you forked it about my offer.  Is it safe to assume there is not a need/want for me to maintain the fork in astral-sh org?  [ from the original author who lost permissions to this repo in April ]

**Comment by CB-GuangyaoXie** [comment]
As per discussed, https://github.com/astral-sh/ruff-action is the new home of this project. Thanks for all the helps. 

This repository will be archived(read-only) very soon. For anyone referencing this repo in your Action jobs, please update them to use `astral-sh/ruff-action`.
