### ISSUE TITLE
Environment variable `RUFF_FORMAT` deprecated in `ruff==0.0.291`

### ISSUE THREAD

**Issue by celynw** [ChartBoost/ruff-action#6]
As of [v0.0.291](https://github.com/astral-sh/ruff/releases/tag/v0.0.291), the environment variable [has been renamed](https://github.com/astral-sh/ruff/commit/bb4f7c681a57f1a0b752fd767c1c75e1fbf878fb). Looks like this action still works without issue, it just raises a warning

> ```
> warning: The environment variable `RUFF_FORMAT` is deprecated. Use `RUFF_OUTPUT_FORMAT` instead.
> ```

I'm not very familiar with actions, so I think it would be better if somebody else handles this change.

Thanks for making this available!

**Comment by brucearctor** [comment]
@celynw -- I don't have time to dig into this at the moment.  I suspect we'd just add another line like: https://github.com/ChartBoost/ruff-action/blob/main/action.yml#L32 to this [ we'd probably want to keep that line, for now, to keep compatibility ].  

I marked as good-first-issue for someone/anyone.  Contributions welcome!
